adafruit/Adafruit_Blinka

src/adafruit_blinka/board/raspi_23.py, src/adafruit_blinka/microcontroller/raspi_23/pin.py
tested all of the board.Dxx pins with an LED
=> Add remaining GPIO to Pi board and quiet GPIO

src/adafruit_blinka/microcontroller/raspi_23/spi.py, src/busio.py
tested with BME280
still hardware SPI only!
=> SPI write/readinto work

src/adafruit_blinka/agnostic/__init__.py, src/bitbangio.py, src/board.py, src/busio.py, src/digitalio.py, src/microcontroller/__init__.py, src/microcontroller/pin.py
Also, rename variables for clarity.
=> Fix machine import when on normal Linux.

src/adafruit_blinka/microcontroller/raspi_23/spi.py, src/busio.py
@kattni this will make LIS3DH work!
=> I2C and SPI fixes to bring more in line with busio

src/adafruit_blinka/microcontroller/raspi_23/i2c.py, src/busio.py
also added start/end buffer slicing which we forgot to do before!
=> add writeto_then_readfrom support for repeated-start i2c transactions

.travis.yml, docs/conf.py, requirements.txt, src/adafruit_blinka/microcontroller/raspi_23/neopixel.py, src/neopixel_write.py
=> initial commit, working code

requirements.txt, setup.py
...we were missing this for `microcontroller/generic_linux/i2c.py`.
=> add Adafruit-PureIO requirement

src/adafruit_blinka/board/beaglebone_black.py, src/adafruit_blinka/board/feather_huzzah.py, src/adafruit_blinka/board/orangepipc.py, src/adafruit_blinka/board/raspi_1b_rev1.py, src/adafruit_blinka/board/raspi_1b_rev2.py, src/adafruit_blinka/board/tritium-h3.py, src/adafruit_blinka/microcontroller/bcm283x/pin.py, src/board.py
Add correct pin definitions for two variants of Raspberry Pi 1.
=> pi 1 pin definitions

requirements.txt, setup.py
check and only try to install spidev on linux (keeps blinka from failing on mac/win)
=> spidev only on linux (where it exists)

src/adafruit_blinka/board/giantboard.py, src/adafruit_blinka/microcontroller/sama5/pin.py, src/board.py, src/busio.py, src/digitalio.py, src/microcontroller/__init__.py, src/microcontroller/pin.py
This PR:
- adds support for the Giant Board linux SBC
=> Add support for Giant Board

src/adafruit_blinka/microcontroller/bcm283x/pin.py
as seen here
https://forums.adafruit.com/viewtopic.php?f=8&t=146375&p=725923#p725923
i tested with hardware too
=> fix for first pi's

src/adafruit_blinka/board/beaglebone_black.py, src/adafruit_blinka/board/beaglebone_pocketbeagle.py, src/adafruit_blinka/microcontroller/am335x/pin.py, src/board.py
WIP
this pull request adds the definitions for the BeagleBoard [PocketBeagle](https://beagleboard.org/pocket)
more discussion about this can be found in #100 
includes changes from [BBB_pinFixes](https://github.com/s-light/Adafruit_Blinka/tree/BBB_pinFixes)
=> PocketBeagle support

src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py
and clean up when we close. now works a lot nicer with simpleio tone
=> fix some sysfs complaints on init or freq change

src/adafruit_blinka/microcontroller/generic_linux/spi.py, src/busio.py
Also fixes an error message in busio.
=> Fixes issue with SPI on Orange Pi Zero and R1

src/adafruit_blinka/microcontroller/ft232h/spi.py
For #172 
This check sort of fell through the cracks for the initial release.
=> Add SPI phase check to FT232H

src/adafruit_blinka/microcontroller/generic_linux/i2c.py
this is the part 2 to fix linux write-then-read :)
=> Multibyteaddr

src/adafruit_blinka/board/microchip_mcp2221.py, src/adafruit_blinka/microcontroller/mcp2221/i2c.py, src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py, src/adafruit_blinka/microcontroller/mcp2221/pin.py, src/analogio.py, src/board.py, src/busio.py, src/digitalio.py, src/microcontroller/pin.py
This has initial working MCP2221 code.
=> Add MCP2221 support.

.travis.yml, requirements.txt, setup.py
@ladyada Here it is, to the extent I understand how the PyPi plumbing works. @kattni look OK to you?
=> Update PyPi requirements for MCP2221

requirements.txt, setup.py
Updated setup.py to check for CI-specific environment variables to fix failing builds.
=> Update setup.py to only install hidapi on non-CI environment

setup.py
This is blocking multiple people from doing work, so I'm going to remove this altogether and we can add it back in later.
=> removed hidapi altogether

README.rst, docs/api.rst, setup.py
This is a potential fix for #206. But I'm not a PyPi expert by any means, so not 100% sure.
Also updated a few other items to reference new analogio module.
=> Additional PyPi and other things for new analogio module

setup.py
For #208 again
Sorry. Missed this bit needed for PyPi deploy.
=> Update pyftdi version for pypi

src/adafruit_blinka/board/pine64.py
While going through testing everything, these changes seemed necessary.
=> Changed pin names from GPIO to D because it feel better

src/busio.py
@makermelissa adding the PINE64 devices I might have add redundant code, so I'm making this PR in order to fix it.
Regards.
=> Remove reduntant code.

src/board.py
BeagleBone Green has same pin headers as Black
=> add BeagleBone Green

setup.py
=> Update Python required version to 3.5

requirements.txt, setup.py, src/adafruit_blinka/microcontroller/generic_linux/spi.py
This should only be merged after PureIO 1.1.0 is release and so it should fail until then. I'm submitting a PR for PureIO testing purposes.
=> Updates to Blinka to use the PureIO SPI library

README.rst, requirements.txt, setup.py, src/adafruit_blinka/board/radxa/__init__.py, src/adafruit_blinka/board/radxa/rockpis.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_analogin.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_analogout.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_pin.py, src/adafruit_blinka/microcontroller/mcp2221/analogio.py, src/adafruit_blinka/microcontroller/rockchip/rk3308/pin.py, src/analogio.py, src/board.py, src/busio.py, src/digitalio.py, src/microcontroller/__init__.py, src/microcontroller/pin.py, src/pulseio.py
I created new Generic SysFS GPIO pin class for this. I also reorganized analogio so it could work without needing custom pins defined like we did with PWMOut.
=> Added Rock Pi S

src/adafruit_blinka/board/greatfet_one.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/analogio.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/i2c.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/pin.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/pwmout.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/spi.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/uart.py, src/analogio.py, src/board.py, src/busio.py, src/digitalio.py, src/microcontroller/__init__.py, src/microcontroller/pin.py, src/pulseio.py
This adds GreatFET One support including GPIO, I2C, SPI, UART, ADC, DAC and PWMOut.
=> Added GreatFET One Support

src/bitbangio.py
=> Display message to linux user to use new Bitbang Library for now

.github/workflows/build.yml, src/__version__.py, src/adafruit_blinka/microcontroller/am335x/sysfs_pwmout.py, src/adafruit_blinka/microcontroller/ft232h/spi.py, src/adafruit_blinka/microcontroller/generic_linux/i2c.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py, src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py, src/adafruit_blinka/microcontroller/mcp2221/pin.py, src/adafruit_blinka/microcontroller/nova/i2c.py, src/adafruit_blinka/microcontroller/nova/pwmout.py, src/adafruit_blinka/microcontroller/nova/uart.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/i2c.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/pin.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/pwmout.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/spi.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/uart.py, src/analogio.py, src/bitbangio.py, src/board.py, src/busio.py, src/digitalio.py, src/micropython.py, src/pulseio.py
=> Fixed pylint to check all files and linted

src/busio.py
=> Fix threading issue that stopped Blinka from working on MicroPython

src/adafruit_blinka/microcontroller/am335x/sysfs_pwmout.py, src/adafruit_blinka/microcontroller/amlogic/meson_g12_common/pin.py, src/adafruit_blinka/microcontroller/bcm283x/pulseio/PulseIn.py, src/adafruit_blinka/microcontroller/generic_linux/i2c.py, src/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py, src/adafruit_blinka/microcontroller/generic_linux/periphery_pin.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_analogin.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_analogout.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_pin.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py, src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py, src/adafruit_blinka/microcontroller/nova/pwmout.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/pin.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/pwmout.py, src/busio.py
Fixes #335. There were also some new PyLint requirements added for Exception chaining, so I updated all those spots.
=> Added missing OneWire as NotImplemented stub

src/board.py
=> Adjusted Pi 1 Model A to use Pi 1 B Rev 2 board def

src/adafruit_blinka/board/nvidia/clara_agx_xavier.py, src/adafruit_blinka/microcontroller/tegra/t194/pin.py, src/board.py
This depends on https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/101
=> Add support for NVIDIA Clara AGX Xavier

src/adafruit_blinka/board/soPine.py, src/board.py, src/busio.py
Introduce SoPine compatibility
=> Added SoPine compatibility

src/adafruit_blinka/board/nanopi/__init__.py, src/adafruit_blinka/board/nanopi/neoair.py, src/board.py, src/busio.py
=> Added NanoPi NEO Air Support

src/pwmio.py
=> Added pwmio module

docs/conf.py, requirements.txt, setup.py
Also updates sysv_ipc to 1.1.0 or higher.
=> Updated Minimum Python to 3.6

requirements.txt, setup.py
=> bump minimum version for Adafruit-PlatformDetect

.pylintrc, src/microcontroller/__init__.py
This is another library that is designed around having duplicate code.
=> Fix Pylint duplicate code checker

src/microcontroller/__init__.py, src/microcontroller/pin.py
This should fix #431, but I don't have the boards to test on. :)
=> Add H5 and H616 to if else block under microcontroller

src/adafruit_blinka/microcontroller/bcm283x/pulseio/PWMOut.py
=> Add a None check for PWMOut deinit

src/adafruit_blinka/board/lubancat/lubancat_stm32mp157.py, src/adafruit_blinka/microcontroller/stm32/stm32mp157/pin.py, src/analogio.py, src/board.py
1\add 'if' block in board.py and analogio.py
2\add board pin description in lubancat_stm32mp157.py
3\add some special pin in stm32mp157/pin.py to support analogio and i2c functions
=> support the lubancat stm32mp157 board.

src/adafruit_blinka/board/pico_u2if.py, src/adafruit_blinka/microcontroller/bcm283x/pulseio/PulseIn.py, src/adafruit_blinka/microcontroller/pico_u2if/analogio.py, src/adafruit_blinka/microcontroller/pico_u2if/i2c.py, src/adafruit_blinka/microcontroller/pico_u2if/neopixel.py, src/adafruit_blinka/microcontroller/pico_u2if/pico_u2if.py, src/adafruit_blinka/microcontroller/pico_u2if/pin.py, src/adafruit_blinka/microcontroller/pico_u2if/pwmio.py, src/adafruit_blinka/microcontroller/pico_u2if/spi.py, src/analogio.py, src/board.py, src/busio.py, src/digitalio.py, src/microcontroller/pin.py, src/neopixel_write.py, src/pwmio.py
- Get firmware UF2 from here: https://github.com/execuc/u2if/releases
- Consult pinout diagram here: https://github.com/execuc/u2if#u2if-pinout
- Set environment variable `export BLINKA_PICO_U2IF=1` (or equiv)
- provides: GPIO, ADC, PWM, I2C, SPI, NeoPixel
Please test and find what breaks. Everything nominally works, but would not be surprised if there are still a few quirks to smooth out.
=> Add Pico u2if

src/board.py
=> Set the I2C and SPI singletons conditionally if pins exist

src/adafruit_blinka/microcontroller/esp8266/pin.py, src/adafruit_blinka/microcontroller/generic_micropython/i2c.py, src/adafruit_blinka/microcontroller/generic_micropython/spi.py, src/adafruit_blinka/microcontroller/rp2040/i2c.py, src/adafruit_blinka/microcontroller/rp2040/pin.py, src/adafruit_blinka/microcontroller/rp2040/spi.py, src/adafruit_blinka/microcontroller/rp2040/uart.py, src/adafruit_blinka/microcontroller/stm32/stm32f405/pin.py, src/busio.py
Fixes #445. Tested with PyBoard and Raspberry Pi Pico.
=> Fix MicroPython and busio

src/adafruit_blinka/microcontroller/rp2040/i2c.py
Fixes #473. This also adds the stop parameters to readfrom_into and writeto. Verified that this still works with the bme280 example.
=> Added more stuff to RP2040 I2C

src/microcontroller/__init__.py
=> Fix docs not passing if microcontroller is imported

.github/workflows/build.yml, setup.py, src/adafruit_blinka/microcontroller/bcm283x/pulseio/PulseIn.py, src/busio.py, src/rainbowio.py
Tested with QTRP2040 running U2IF.
=> Add rainbowio to Blinka.

src/keypad.py
This is a complete implementation.
=> Added keypad module

.github/workflows/release.yml, setup.py, src/board.py
This supersedes https://github.com/adafruit/Adafruit_Blinka/pull/508
=> Added versioning to board

setup.py
After testing #548 and seeing that didn't fix it, I found out the file also needs to be added to setup.py, so this PR does that.
=> Fix libgpiod further by updating setup.py

src/usb_hid.py
This PR is going to provide a usb_hid adapter using usb gadget. It is not yet complete, but i would like to collect early input on it.
=> usb_hid module

README.rst, src/usb_hid.py
using multiple device types [Device.KEYBOARD, Device.MOUSE] caused error, this solves that issue.
=> solve issues with multiple hid devices on one gadget

setup.py
=> Added usb_hid to py_modules in setup.py

src/adafruit_blinka/board/hardkernel/odroidm1.py, src/adafruit_blinka/microcontroller/rockchip/rk3568b2/__init__.py, src/adafruit_blinka/microcontroller/rockchip/rk3568b2/pin.py, src/board.py, src/digitalio.py, src/microcontroller/pin.py
Hi, I would like to ask for a review of my attempt to add an Odroid M1 board.
=> Adding Odroid M1 

src/adafruit_blinka/board/feather_epd_u2if.py, src/adafruit_blinka/microcontroller/rp2040_u2if/i2c.py, src/adafruit_blinka/microcontroller/rp2040_u2if/spi.py, src/board.py, src/busio.py, src/neopixel_write.py, src/pwmio.py
Adding support for the Feather ThinkInk. Tested with u2if firmware
=> Adding support for Feather ThinkInk

src/adafruit_blinka/board/feather_can_u2if.py, src/adafruit_blinka/board/feather_rfm_u2if.py, src/adafruit_blinka/microcontroller/rp2040_u2if/i2c.py, src/adafruit_blinka/microcontroller/rp2040_u2if/spi.py, src/board.py, src/busio.py, src/neopixel_write.py, src/pwmio.py
Adding support for CAN and RFM Feathers to use with U2IF
=> Adding support for CAN and RFM Feathers

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new_board_request.md, .pre-commit-config.yaml, .pylintrc, requirements.txt, setup.py, src/adafruit_blinka/microcontroller/am335x/sysfs_pwmout.py, src/adafruit_blinka/microcontroller/amlogic/a311d/pulseio/PulseIn.py, src/adafruit_blinka/microcontroller/amlogic/meson_g12_common/pulseio/PulseIn.py, src/adafruit_blinka/microcontroller/bcm283x/pulseio/PulseIn.py, src/adafruit_blinka/microcontroller/ftdi_mpsse/mpsse/spi.py, src/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py, src/adafruit_blinka/microcontroller/generic_linux/sysfs_pin.py, src/adafruit_blinka/microcontroller/generic_micropython/spi.py, src/adafruit_blinka/microcontroller/nova/__init__.py, src/adafruit_blinka/microcontroller/nxp_lpc4330/pwmout.py, src/adafruit_blinka/microcontroller/rp2040/spi.py, src/adafruit_blinka/microcontroller/rp2040/uart.py, src/board.py, src/digitalio.py, src/microcontroller/__init__.py, src/microcontroller/pin.py, src/usb_hid.py, test/src/testing/universal/i2c.py
This informs to submit a new board request if their board isn't supported, add issue templates and updates the versions in the pre-commit config. Fixes #701.
=> Add issue templates and update pre-commit config

README.rst
Fixes #600. I replaced the usage example with something more practical.
=> Update Usage Example in Readme

src/adafruit_blinka/microcontroller/amlogic/meson_g12_common/pin.py
=> Fix issue where meson_g12_common pin failed on older libgpiod

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/new_board_request.md, src/adafruit_blinka/microcontroller/generic_linux/i2c.py, src/busio.py
Fixes #682. Also improves issue template messages.
=> Display a message if user tries to set freq on linux

src/adafruit_blinka/microcontroller/alias.py, src/adafruit_blinka/microcontroller/rockchip/rk3566/pin.py, src/adafruit_blinka/microcontroller/rockchip/rk3568b2/pin.py, src/pulseio.py, src/pwmio.py
PlatformDetect:
- https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/333
=> To support pwm on ODROIDs

src/adafruit_blinka/__init__.py, src/adafruit_blinka/microcontroller/bcm283x/pulseio/PulseIn.py
Fixes #748. Fixes #752. Tested on Pi 5.
=> Fix pulsein for the Pi 5 and make lockable silent

src/pwmio.py
=> Fix PWMIO import bug

src/adafruit_blinka/board/luckfox/luckfoxpico.py, src/adafruit_blinka/board/luckfox/luckfoxpico_plus.py
PicoPlus changed from RV1106 to RV1103
=> PicoPlus changed from RV1106 to RV1103

src/adafruit_blinka/board/orangepi/orangepipc2.py, src/adafruit_blinka/microcontroller/allwinner/h5/pin.py, src/board.py
added orangepipc2 board to blinka
=> added orangepipc2 board

src/adafruit_blinka/microcontroller/rockchip/rk3399/pin.py
Changed with reference to RK3399 data sheet.
=> Fixed PWM definition

src/adafruit_blinka/__init__.py
=> Move tomllib imports to function so it works on MicroPython
