adafruit/Adafruit_Blinka

.travis.yml
src/adafruit_blinka/microcontroller/raspi_23/spi.py

**Adding requested changes from previous pr:**
> runtime error should have a message explaining what went wrong
`raise RuntimeError('Buffer slices must be of equal length.')`
> checks if in_end/out_end is none and have them set to the 'default' len(array)
```
if out_end is None or in_end is None:
out_end = len(buffer_out)
in_end = len(buffer_in)
```
>  use the out_start & out_end ranges here to limit what is sent
`            data = self._spi.xfer(list(buffer_out[out_start:out_end]))
`
> use the in_start & in_end ranges here to put the data in the right section of the buffer_in array
`            for i in range(len(buffer_in[in_start:in_end])): # 'readinto' the given buffer
`

Write_ReadInto PR Review Changes

---

src/adafruit_blinka/microcontroller/raspi_23/spi.py

Found this while testing the MAX31865:
```
(.env) $ python3 ./max31865_simpletest.py  
Traceback (most recent call last): 
File "./max31865_simpletest.py", line 15, in <module> 
sensor = adafruit_max31865.MAX31865(spi, cs) 
File "/home/pi/blinkenlight/.env/lib/python3.5/site-packages/adafruit_max31865.py", line 105, in __init__ 
config = self._read_u8(_MAX31865_CONFIG_REG) 
File "/home/pi/blinkenlight/.env/lib/python3.5/site-packages/adafruit_max31865.py", line 119, in _read_u8 
with self._device as device: 
File "/home/pi/blinkenlight/.env/lib/python3.5/site-packages/adafruit_bus_device/spi_device.py", line 83, in __enter__ 
phase=self.phase) 
File "/home/pi/blinkenlight/.env/lib/python3.5/site-packages/busio.py", line 104, in configure 
miso=Pin(self._pins[2].id) 
File …
```

fix raspi spi access of mode constants (was missing a "self")

---

examples/bbb_digitalio.py

Example of using digitalio to blink a LED on [BeagleBone Black](https://www.adafruit.com/product/1876)
Wire the circuit as follows: 
* connect anode (+) lead of LED to [P9.12 pin](https://elinux.org/Beagleboard:Cape_Expansion_Headers)
* connect cathode (-) lead to 1K Ohm resistor
* connect that 1K Ohm resistor to [DGND (P9.1)](https://elinux.org/Beagleboard:Cape_Expansion_Headers)

Add example to blink LED on BeagleBone

---

src/adafruit_blinka/board/beaglebone_black.py
src/adafruit_blinka/microcontroller/beaglebone_black/pin.py
src/busio.py

FYI - THIS IS WORK IN PROGRESS.  ADDITIONAL COMMITS WILL BE ADDED TO THIS PR.
Refer to header default pin modes
http://beagleboard.org/static/images/cape-headers.png
P9_17 (SPI0_CSO => CE0) enables peripheral device
P9_18 (SPI0_D1 => MOSI) outputs data to peripheral device
P9_21 (SPIO_DO => MISO) receives data from peripheral device
P9_22 (SPI0_SCLK => SCLK) outputs clock signal
Use config-pin to set pin mode for SPI pins
https://github.com/beagleboard/bb.org-overlays/tree/master/tools/beaglebone-universal-io
config-pin p9.17 spi_cs
config-pin p9.18 spi
config-pin p9.21 spi
config-pin p9.22 spi_sclk

Add preliminary SPI support for BeagleBone Black

---

requirements.txt
setup.py

We're looking to dispense with this, but in the meantime I think it's breaking a fair number of installs.

add RPi.GPIO to requirements

---

src/adafruit_blinka/board/tritium-h3.py
src/adafruit_blinka/microcontroller/allwinner_h3/pin.py

This adds only the board file and extra needed pins to support the Libre Computer Tritium family: https://libre.computer/products/boards/all-h3-cc/ .  Obviously running on the board will not work with this patch alone, the various detects need put in place.
As the board detection is in flux I haven't pushed that part, and the UART port defined by the H3 file is OPi-PC specific, but will work if you have the pin map of the Tritium board handy, mentioned in https://github.com/adafruit/Adafruit_Blinka/issues/62
Armbian Board Name "tritium-h3"

Add board support files for Tritium H3

---

src/busio.py

Fix for #74.
```python
pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board, busio
>>> uart = busio.UART(board.TXD, board.RXD)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/pi/Adafruit_Blinka/src/busio.py", line 153, in __init__
raise RuntimeError('busio.UART not supported on this platform.')
RuntimeError: busio.UART not supported on this platform.
>>> 
```

Add linux detect to busio.UART

---

src/adafruit_blinka/microcontroller/generic_linux/spi.py
src/busio.py

Have ported the micropython nRF24L01 driver over to circuitpython today, but found issues with the fact SPI `readinto` ignored the `write_value` parameter. It's advertised there, so it's frustrating it does nothing.
These changes ensure that value actually works. I've tested this on a pi zero successfully. Not sure how it effects boards where `machine.SPI` is used, rather than the `generic_linux.SPI` driver.

Ensure that the write_value passed into readinto is actually used

---

setup.py

Fixes #91 by adding `__init__.py` to the package and adding libgpiod_pulsein to setup.py

Include adafruit_blinka.microcontroller.bcm283x.pulseio in package

---

src/board.py

will default to the names we have for I2C and SPI default pins

add I2C and SPI singletons for some drivers

---

setup.py

While Blinka does not currently work on Microsoft Windows, it should be possible to install it as managing dependencies with pipenv requires that no install-time errors occur.
The current blocker to installation is a dependency on `sysv_ipc` which only works on POSIX-like operating systems. This change marks the dependency as being conditional on the install target not being Windows (this does not affect people running under cygwin or Windows Subsystem for Linux).
This does not add support for Windows, any attempt to use this code on Windows will result in exceptions being raised or non-functional code. This just makes it possible to manipulate pipenv environments that contain a transitive dependency on Blinka.
For more information on context see …

Allow installation on Windows

---

src/adafruit_blinka/microcontroller/generic_linux/spi.py

Avoid trying to set SPI_NO_CS mode bit when the chip is AM3358 as this
will always fail as Linux kernel driver omap2_mcspi does not support it.
This applies to the BeagleBone Black and PocketBeagle.

do not set SPI_NO_CS bit when chip is AM3358 #104

---

src/adafruit_blinka/microcontroller/am335x/pin.py

Change SPI port index because SPI0 is `/dev/spidev1.x` and SPI1 is `/dev/spidev2.x` on both:
* the current recommended [BeagleBoard.org Debian image](http://beagleboard.org/latest-images): Debian 9.5 (Stretch) from 2018-10-07
* the newest [Debian 9.8 (Strecth) snapshot from 2019-04-07](https://elinux.org/Beagleboard:BeagleBoneBlack_Debian#Stretch_Snapshot_iot)
This change is to fix issue #106: inconsistent spidev index on AM335x-based boards like BeagleBone Black and PocketBeagle.

change SPI index for BeagleBone/PocketBeagle #106

---

src/adafruit_blinka/board/coral_edge_tpu.py
src/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py
src/adafruit_blinka/microcontroller/generic_linux/spi.py
src/adafruit_blinka/microcontroller/nxp_imx8m/pin.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

uart #3 not available and remaining pins are I2S or PWM

Google Coral support for the i2c, spi, and GPIO pins. 

---

src/adafruit_blinka/board/coral_edge_tpu.py
src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py
src/adafruit_blinka/microcontroller/nxp_imx8m/pin.py
src/pulseio.py

can be used with any linux device that has sysfs pwm chips

add a periphery-based sysfs pwmout object - tested with LED and servo

---

src/adafruit_blinka/board/giantboard.py
src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py
src/adafruit_blinka/microcontroller/sama5/pin.py
src/pulseio.py

This pull request:
- Add alternate pin names
- Add sysfs pwm pins
- Update pulseio.py to include Giant Board
- Fix import errors for sysfs pwm

Update Giant Board alt pins names and add sysfs pwm support

---

src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py

This pull request:
- Fix sysfsPWM write error on export
After some more testing, I've found this line to be my culprit for not allowing the PWM to be used. After commenting the line, everything appears to work as it should.
This line `self._set_enabled(False)` and this line `self.duty_cycle = 0` throws an `Invalid argument` when trying to write to the device:
```
Traceback (most recent call last):
File "pwmtest.py", line 5, in <module>
led = pulseio.PWMOut(board.PWM1, frequency=5000, duty_cycle=0)
File "/usr/local/lib/python3.5/dist-packages/Adafruit_Blinka-1.3.3.dev2+gf599d17.d20190519-py3.5.egg/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py", line 55, in __init__
self._open(pin, duty_cycle, frequency, variable_frequency)
File …
```

Fix for sysfs PWM `Invalid argument` write error when trying to setup the device.

---

src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py

Fixes #120.
I cannot test this, since `pulseio.PWMOut` is only available for the Google Coral and Giant Board. Neither of which I have.

Add 'deinit()' Function To PWMOut

---

src/adafruit_blinka/microcontroller/generic_linux/spi.py

This pull request:
- Adds SAMA5 to set_no_cs method

Add SAMA5 to set_no_cs to allow SPI device to setup.

---

src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py

Addressing https://github.com/adafruit/Adafruit_Blinka/issues/125
Tested on Google Coral
```
>>> pwm.period = 1
>>> pwm.period
1.0
```

Add property to period method

---

src/pulseio.py

Since there's nothing in `/sys/class/pwm` and no overlays in the latest mainline kernel release of armbian, I'm going to remove this for now.

Removed Odroid C2 from pulseio

---

src/busio.py

Resolves https://github.com/adafruit/Adafruit_Blinka/issues/130 for RPI boards running ubuntu/arm64 if using, for instance BLINKA_FORCEBOARD=RASPBERRY_PI_3B_PLUS and BLINKA_FORCECHIP=BCM2XXX to bypass board detection failure in Adafruit_Python_PlatformDetect.

Allows Raspberry Pi boards on arm64 to work w/ BLINKA_FORCEBOARD

---

requirements.txt
setup.py
src/adafruit_blinka/board/jetson_nano.py
src/adafruit_blinka/board/jetson_tx1.py
src/adafruit_blinka/board/jetson_tx2.py
src/adafruit_blinka/board/jetson_xavier.py
src/adafruit_blinka/microcontroller/generic_linux/spi.py
src/adafruit_blinka/microcontroller/tegra/t186/pin.py
src/adafruit_blinka/microcontroller/tegra/t194/pin.py
src/adafruit_blinka/microcontroller/tegra/t210/pin.py
src/busio.py

Support SPI controllers on Jetson.
Depend on Jetson.GPIO and stop hard-coding its expected installation path.
Add missing D7 pin definition on Jetson TX2.

Jetson SPI support and Jetson.GPIO requirement

---

requirements.txt
src/adafruit_blinka/microcontroller/generic_linux/spi.py

This fixes #144.
I'm not sure if this is the best approach or if we should just tell the user to update SPIDEV to latest version in the error.

Update requirements for SpiDev >= 3.4

---

setup.py

setup.py currently assumes that all ARMv6/7 platforms are an RPi, and all
AArch64 systems are a Jetson. This is untrue, since:
a) All recent ARM Linux systems are one of those types, and Blinka
supports plenty of Linux systems besides the Pi and Jetson.
b) Recent Pis are quite capable of running an AArch64 user-space, and
Jetson could run an ARMv7 user-spcae.
Solve this by enhancing setup.py to detect which specific system it's
running on, using the device tree compatible value. (Other mechanisms
could be used for other types of system in the future if required.) The
active dependency list is calculated based on this information.
There have been some bugs reported[1] that could only have occurred if
the previous platform limitations in setup.py's install_requires were not
correctly …

setup.py: Runtime dependency determination

---

src/board.py

According to the schematics for the original Pis posted at https://www.raspberrypi.org/app/uploads/2012/04/Raspberry-Pi-Schematics-R1.0.pdf, the connections to the chips for Pi 1 Model A and Pi 1 Model B Rev 1 should be exactly the same. So if Pi 1 Model A is detected, I'm using the Pi 1 Model B Rev 1 pinouts in this PR. I don't have the Pi 1 Model A on hand, so I'll have a user test it.

Adds Raspberry Pi 1 Model A

---

requirements.txt
src/adafruit_blinka/board/ftdi_ft232h.py
src/adafruit_blinka/microcontroller/ft232h/i2c.py
src/adafruit_blinka/microcontroller/ft232h/pin.py
src/adafruit_blinka/microcontroller/ft232h/spi.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/pin.py

Adds basic I2C, SPI, and GPIO functionality using FT232H. 
* Relies on [pyftdi](https://pypi.org/project/pyftdi/) library for actual FT232H control.
* To use, set environment variable `BLINKA_FT232H`. Then proceed as normal.
* Pin names match silk on FT232H breakout.
* Currently no support for multiple FT232H's. The first one found on the bus is used, via URL `ftdi:///1`.
* GPIO access is provided by I2C and SPI specific interfaces. To make this transparent, the class level `ft232h_gpio` in `microcontroller.ft232h.pin.Pin` is used to hold the current one. This is then changed in the `I2C` and `SPI` class constructors. Is there a better way?
* Pins D0-D3 are simply ignored for GPIO. D3 could be used in I2C mode, but probably not worth confusion and extra code for one extra GPIO pin.
* The …

Add basic FT232H support.

---

src/adafruit_blinka/microcontroller/ft232h/spi.py

pyftdi has a limit of total size of SPI data that can be written in one operation. This breaks larger data up into multiple chunks and writes.
Sloth love Chunk!

Chunkify FT232H SPI write

---

src/adafruit_blinka/microcontroller/ft232h/spi.py
src/adafruit_blinka/microcontroller/generic_linux/spi.py
src/busio.py

For #161 
Note that there is also some refactoring of the FT232H SPI internals. This was motivated by discovering that subsequent changes to frequency were not taking effect. Now a port instance is kept around and changed as needed. These changes were tested to still work with a BME280 and also SPI driven NeoPixels.
**Querying SPI frequency on a PC with FT232H:**
```
:~$ python3
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> spi = board.SPI()
>>> spi.frequency
100000 
>>> 
```
**Querying SPI frequency on a RPI:**
```
pi@raspberrypi:~ $ python3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more …
```

Add SPI frequency property

---

src/adafruit_blinka/microcontroller/generic_linux/spi.py

Previous version did not catch `AttributeError: 'SPI' object has no attribute 'chip'`, which occurs, e.g., on RPi3 running Debian Buster.

Fix missing attribute exception catch for 'SPI.chip' on RPi

---

src/busio.py

ValueError makes more sense since the feature is actually implemented.
This fixes https://github.com/adafruit/Adafruit_CircuitPython_WS2801/issues/6 in that it doesn't just quit, but I haven't tested with lights.

Changed error to more appropriate type

---

src/adafruit_blinka/board/beaglebone_pocketbeagle.py
src/adafruit_blinka/microcontroller/am335x/pin.py
src/adafruit_blinka/microcontroller/am335x/sysfs_pwmout.py
src/pulseio.py

Add PWMOut for PocketBeagle which has the AM3358 SoC to resolve issue #159 
Unfortunately, [the generic linux PWMOut implementation](https://github.com/adafruit/Adafruit_Blinka/tree/master/src/adafruit_blinka/microcontroller/generic_linux) will not work as [the BeagleBoard.org kernel has a patch](https://github.com/RobertCNelson/bb-kernel/blob/am33x-v4.11/patches/drivers/pwm/0001-pwm-Create-device-class-for-pwm-channels.patch) which changes the naming scheme for PWM channels.
The patch changes the naming scheme from `pwmchipX/pwmY` to `pwmchipX/pwm-X:Y`.  The PocketBeagle has these PWM outputs:
```
/sys/class/pwm/pwmchip0/pwm-0:0/period
/sys/class/pwm/pwmchip0/pwm-0:1/period
/sys/class/pwm/pwmchip2/pwm-2:0/period
/sys/class/pwm/pwmchip2/pwm-2:1/period …
```

Add PWMOut for PocketBeagle

---

src/adafruit_blinka/microcontroller/tegra/t210/pin.py

Reverts adafruit/Adafruit_Blinka#176
I need to undo this. Changes #175 and #176 break the Jetson TX1.

Revert "Update pin.py"

---

src/adafruit_blinka/board/jetson_nano.py

Reverts adafruit/Adafruit_Blinka#175
I need to undo this. Changes #175 and #176 break the Jetson TX1.

Revert "Update jetson_nano.py"

---

src/busio.py

This is a pull request for issue #40 at https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15/issues/40#issuecomment-548527569, which it turns out is best to fix in this project.
I have added a thread.RLock so that only one thread can access the ADS as once, preventing deadlocks. I haven't been able to make the original code crash very easily, but I can confirm that it does, after a similar fix downstream in my project resolved the issue. As it is a race condition, I am unsure how to provide a test program to demonstrate the fix, but existing code seems to work fine with this modification.

Add a lock for thread safety when the I2C class is used in a with statement

---

setup.py

Spidev was specified to be >= 3.4 in requirements,txt, but not setup.py which resulted in people having SPIDEV 3.3 installed. This should fix it.

Added spidev >= 3.4 in setup.py

---

src/micropython.py

Thanks to https://github.com/adafruit/circuitpython/pull/2271 and https://github.com/adafruit/circuitpython/pull/2282, CircuitPython 5 will support the `micropython.native` decorator (and friends, if enabled). This adds similar behavior to the Blinka library. It matches the behavior of a board that doesn't have these optimizations enabled:
* `native` will do nothing.
* `viper` will raise a `SyntaxError`..
* `asm_thumb` will raise a `SyntaxError`.
This will ensure that drivers written for CircuitPython 5 that have optional optimizations will work as expected.

Add stubs for micropython.natve, viper, and asm_thumb

---

src/adafruit_blinka/board/raspi_40pin.py
src/adafruit_blinka/microcontroller/bcm283x/pin.py
src/busio.py

I added i2c-3, which uses SDA and SCL as well. I have updated the I2C code to go with the first one that successfully loads rather than the first that pin-matches and have tested this on i2c-1 and i2c-3 with an Adafruit PiOLED. I also exposed Pins D0 and D1 on the board definition because it seems pointless having i2c-0 defined using D0 and D1 if it can't even be used.

Blinka will now work with i2c-3 automatically

---

src/board.py

It still imports from adafruit_blinka.board.beaglebone_black because it is otherwise
compatible except for the increased temperature range.

Added BEAGLEBONE_BLACK_INDUSTRIAL to board.py

---

src/adafruit_blinka/board/raspi_1b_rev1.py
src/adafruit_blinka/board/raspi_1b_rev2.py
src/adafruit_blinka/board/raspi_40pin.py
src/adafruit_blinka/board/raspi_cm.py

The example code relies on the existence of `RX` and `TX`, but the naming in the raspberry pi files is inconsistent (`RXD` and `TXD`).

Add RX TX aliases for raspberry pi

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

errors throw an exception, a little more elegant than trying to check status

fix mcp2221 i2c scan

---

src/adafruit_blinka/microcontroller/ft232h/i2c.py
src/busio.py

Fix for #174 
```python
>>> import board
>>> import adafruit_msa301
>>> msa = adafruit_msa301.MSA301(board.I2C())
```
```python
>>> import board
>>> import busio
>>> import adafruit_msa301
>>> i2c = busio.I2C(board.SCL, board.SDA, frequency=100000)
>>> msa = adafruit_msa301.MSA301(i2c)
```

Add frequency for FT232H I2C

---

requirements.txt

Since having hidapi in requirements.txt causes anything with a Blinka dependency to fail that doesn't install libusb (see #202), the easiest thing to do is leave it out of requirements.txt, but leave it in setup.py.
The method we have the user following (pip3 install adafruit-blinka) will still have it work because that uses setup.py whereas the repos use `pip3 install -r requirements.txt`.
Fixes #202.

Removing hidapi from requirements to fix Travis

---

requirements.txt
setup.py

If we can get the specific for each board such as detecting the Onion running openwrt, we can add specific requirements in another PR like we did for the RPi-GPIO and Jetson-GPIO.

Updated to not install spidev automatically on the mips platform

---

requirements.txt
src/adafruit_blinka/microcontroller/ft232h/i2c.py

Fix for #208 
pyftdi made API breaking changes at version 0.40.0 ([more info](https://eblot.github.io/pyftdi/index.html#major-changes)). This PR updates requirements to force to new API version and updates Blinka to use it.
Tested with a TSL2591:
```python
$ python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> import adafruit_tsl2591
>>> tsl = adafruit_tsl2591.TSL2591(board.I2C())
>>> tsl.lux
326.82431999999994
```

FT232H updates for pyftdi API changes

---

src/adafruit_blinka/board/orangepipc.py
src/adafruit_blinka/board/orangepir1.py
src/adafruit_blinka/board/orangepizero.py
src/adafruit_blinka/board/tritium-h3.py
src/adafruit_blinka/microcontroller/allwinner/__init__.py
src/adafruit_blinka/microcontroller/allwinner/a64/__init__.py
src/adafruit_blinka/microcontroller/allwinner/a64/pin.py
src/adafruit_blinka/microcontroller/allwinner/h3/__init__.py
src/adafruit_blinka/microcontroller/allwinner/h3/pin.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

Hey there!
Sorry if this PR comes out of the blue but I'm making this refactor in order to have all `AllWinner` chip defined within the same module for further implementations.
I'm planning to add the `A64` on it after the PR pending on the `Adafruit_Python_PlatformDetect` library is merged.
Regards.
P.D: I know nobody asked about this PR but IMHO seems like more organized as in the `amlogic` one.

Simple refactor to place all AllWinner boards within the same module

---

src/board.py

I'm adding the some boards from Orange Pi which have the same chip (H3) as the one already defined.
Since the pinout is the same as the Orange Pi PC was easy to just import it when one of the boards added into Adafruit_PlatformDetect.
This PR correspond to issue #226 
If any change is needed, just let me know.

Add Orange Pi boards (One, Lite, PC Plus, Plus 2E)

---

requirements.txt
setup.py

Released a refactored Platform Detect only to discover the Blinka-side PR was broken, so temporarily pointing to last working Blinka version.

Temporarily point to older platform detect

---

src/adafruit_blinka/microcontroller/ft232h/i2c.py
src/adafruit_blinka/microcontroller/ft232h/pin.py
src/adafruit_blinka/microcontroller/ft232h/spi.py

By changing the search URL to ftdi://ftdi:ft232h/1, pyftdi will open the first ft232h it finds, rather than the first ftdi device it finds. This is useful when other usb-serial converters are in use in addition to the ft232h.
Fixes issue #227

Changed FT232H search url

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

Fixes some things on Windows, breaks others. To use, set environment variable `BLINKA_MCP2221_HID_DELAY` to some small value. On test machine, a value of about `0.005` seemed to work.

Add HID delay

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

Another attempt at fixing things on some Windows machines.
On test machine, noticed that the call to `reset` which is done in the `init` caused the machine to make the "something removed/connected" sound. The call to `_hid.open()` done in `reset` would succeed, but the next call to `_hid.xfer()` would fail. Added a print out of the actual underlying error and it was "Device not connected". Huh? You opened it OK but still think it's not connected?
Moved the post-reset delay to within the `reset()` function and before the calls to re-open it. Settable via env variable `BLINKA_MCP2221_RESET_DELAY`, but with default that worked on test machine. This made things work* on the test machine even with setting `BLINKA_MCP2221_HID_DELAY` to `0`.
*MLX90640 still not working for some reason

Change MCP2221 reset behavior

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

Setting "final" values based on feedback. I think the highest reported value to get things working was 0.2. So setting to 0.5. But fine with cranking that up higher if it seems worth it. It's always overrideable via envvar.

MCP2221 delay tuning

---

src/board.py

Beaglebone black wireless was not supported as a device, but I am using it with i2c on my beaglebone black wireless by simply adding it as a possible device.

Added Beaglebone Black Wireless as a device.

---

src/adafruit_blinka/board/clockworkcpi3.py
src/adafruit_blinka/microcontroller/allwinner/a33/__init__.py
src/adafruit_blinka/microcontroller/allwinner/a33/pin.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

The Clockwork Pi Gameshell is a hackable retro gaming device which exposes some GPIO/I2C/SPI ports and runs on a Allwinner R16/A33 SoC.

Add Clockwork Pi board

---

.github/workflows/build.yml

PR #282 is running into an issue with the following error message:
```
##[error]fatal: reference is not a tree: 539962c4c3c088797d02202922a9c51534b77bdf
##[error]Git checkout failed with exit code: 128
##[error]Exit code 1 returned from process: file name '/home/runner/runners/2.169.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
```
According to https://github.com/actions/checkout/issues/23, this particular issue is fixed in V2, so this PR makes it use V2.

Set checkout repo to V2 since it fixes an issue

---

src/board.py

Add support for the Orange PI 2 using the existing orange pi pc class.
Depends on adafruit/Adafruit_Python_PlatformDetect#75

Add Orange PI 2 constant (Attempt #2)

---

src/adafruit_blinka/microcontroller/am335x/pin.py

I attached a MAX31865 to BB. However, the existing code was attempting to open /dev/spidev2.0 whilst the correct device has to be /dev/spidev1.0
I traced the issue to the spiPorts being enumerated as 1 and 2, rather than 0 and 1

Using SPI1 on Beaglebone Black

---

src/adafruit_blinka/microcontroller/nxp_imx8m/pin.py

The spiId used for the Coral board changed with Day release of Mendel. This helps correct #306

Correct the spiId for the Coral Board

---

src/adafruit_blinka/microcontroller/bcm283x/pulseio/PWMOut.py
src/pulseio.py

Fixes #37. Tested using D26 (a GPIO without built-in PWM) using this script https://learn.adafruit.com/circuitpython-on-google-coral-linux-blinka/pwm-outputs-servos.

Added PWMOut functionality for the Raspberry Pi

---

src/adafruit_blinka/microcontroller/bcm283x/pulseio/PWMOut.py

Fixed a bug with PWM that was resulting in an incorrect duty cycle value being used. Also I changed the error message to be more meaningful to the user.

Fixed a PWM Bug for the Raspberry Pi

---

src/adafruit_blinka/microcontroller/ft232h/spi.py

For #326 
Re-running test from issue thread:
And to exercise things a little more:
```python
import board
import digitalio
BUFFER = bytearray([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
spi = board.SPI()
cs = digitalio.DigitalInOut(board.C0)
cs.direction = digitalio.Direction.OUTPUT
cs.value = True
spi.try_lock()
cs.value = False
spi.write(BUFFER, start=6, end=11)
cs.value = True
spi.unlock()
```

Fix FT232H SPI chunkification

---

setup.py

This was causing issue on the STM32MP1 which apparently doesn't have gcc available to compile it and doesn't even need sysv_ipc.

Move sysv_ipc to only install on Raspberry Pi

---

requirements.txt
setup.py
src/adafruit_blinka/board/pyboard.py
src/adafruit_blinka/microcontroller/stm32/stm32f405/pin.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

This will require https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/97 to be merged in and PlatformDetect release 2.15.1 to be performed before it will pass the checks.

Updated for STM32->STM32F405 PlatformDetect chip rename

---

.github/workflows/build.yml
src/adafruit_blinka/__init__.py
src/busio.py
test/src/testing/adafruit_blinka.py

For some reason Black was still tied to an older version. This fixes it so it's like the other libraries.

Allow latest release of black to run

---

examples/mcps_busio_i2c.py

I am working on a project which requires the use of multiple MCP2221 + MLX90640 on a single host. It looked like it was not possible with the current code, so I made this example which shows how it can be accomplished without modifying any code of this library. You can then create different I2C objects independently, in my case MLX90640, and use them normally.
- Redefine existing classes to be able to connect with device path
- Use MCP2221 which is created on import.
- Connect to other MCP2221, if any.
- Print ids (made for mlx90640)

Enable support for multiple mcp2221

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

I have an MCP2221 that I could not for the life of me get to work with Blinka until I by-hand skipped the `_reset` stage. On my system (Ubuntu 20.04 on kernel 5.8.10), for whatever reason the reset process takes forever, sometimes >15 seconds. But for many of my use cases I don't really need to bother with the reset process anyway since I'm often just plugging it once so that I know it's already been reset.
So this PR adds a convenient way to skip the reset phase: set the `BLINKA_MCP2221_RESET_DELAY` environment variable to any negative number.  If you prefer not to overload envars this way I could also change it to ust a variable like `BLINKA_MCP2221_SKIP_RESET` or something like that instead.

add option to skip reset on MCP2221

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

This adds a runtime exception in the I2C read call if the number of retries is exceeded. This mimics the write call. Currently the code continues even if the retries are exceeded. I ran into this as an issue when trying the SI7021. The SI7021 NACKs reads when it isn't ready to provide a temperature and the retries can happen so fast that it is never ready in time for a valid value.

If the number of retries is exceeded raise an error

---

src/adafruit_blinka/microcontroller/bcm283x/pulseio/PulseIn.py

Trying to debug adafruit/Adafruit_CircuitPython_DHT/issues/52 I stumbled across this issue. On high system load, bcm283x/pulseio/PulseIn.py will get itself into trouble due to pure impatience:
When requesting data from libgpiod_pulsein via the message queue, we
always expect an answer. Prematurely stopping to wait for an answer can
only do harm. If we do not read the expected answer from the mq, it will
stay there and be read (falsely) as an answer to the following request.
Example:
* We request a pulse length by sending '^'.
* Due to high system load, libgpiod_pulsein does not send a response in
time.
* We timeout with a RuntimeError. This is verly likely ignored by the
calling code since RuntimeErrors are thrown with every invalid
reading such that the calling code _has to_ ignore these …

Do not prematurely stop waiting for an answer from the message queue

---

src/adafruit_blinka/board/pineH64.py
src/adafruit_blinka/microcontroller/allwinner/h6/__init__.py
src/adafruit_blinka/microcontroller/allwinner/h6/pin.py
src/board.py

I have added the "microcontroller" file and "board" file for the Allwinner H6 based PineH64. I believe these are the only necessary files for Blinka compatibility.
I followed the guide provided by Adafruit at the following link: 
https://learn.adafruit.com/adding-a-single-board-computer-to-blinka/
I will also be creating a pull request for adafruit_platformdetect to add PineH64 detection.

Adding PineH64 SBC support 

---

src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py

This gives udev time to respond to the device event. Without this,
the subsequent attempts to modify pin properties will fail when
depending on udev rules to apply new user permissions.
This code is essentially copied from python-periphery, as was most
of this file (both MIT licenced). Although it appears sergeev added
this loop recently, compared to when this code was originally cloned.

Add timout loop after exporting the PWM pin.

---

src/busio.py

Minor changed suggested in #391 , but probably not an actual fix for that specific issue. Current default is 400kHz, but 100kHz is generally accepted as the more "standard" clock speed. So this change is simply to bring in line with that.

Change default I2C clock frequency

---

src/adafruit_blinka/microcontroller/mcp2221/i2c.py
src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

Mainly just a cosmetic change to deal with #391 . As is, this function does not seem to work reliably when called after the initial setup. But it works OK as currently used from constructor. So for now, just adding `_` to indicate it's for internal use only. And it was already buried in the MCP class, so it's internally internal? Anywho, nothing broken.
I2C scan with a VEML6075 attached:
```python
~$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import board
>>> i2c = board.I2C()
>>> i2c.scan()
[16]
>>> 
```

Privitize `i2c_configure` in MCP2221 class

---

examples/analog_in.py
src/adafruit_blinka/board/lubancat/__init__.py
src/adafruit_blinka/board/lubancat/lubancat_imx6ull.py
src/adafruit_blinka/microcontroller/nxp_imx6ull/pin.py
src/analogio.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py
src/pulseio.py

This is the pins and board support for LubanCat i.MX6ULL.
Its contains ditital IO, busio, pulseio and analog in.
And I added an analog in example to make testing easier.
I‘ve added platform detect for LubanCat: https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/130

Add support for LubanCat i.MX6ULL board

---

src/adafruit_blinka/board/beagleboard/beaglebone_ai.py
src/adafruit_blinka/microcontroller/dra74x/pin.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

GPIO, I2C, and UART are functional in this PR. 
Even though I was able to figure out how to enable it, I could not get SPI working and this will likely involve creating a custom device tree to enable or possible some other means. Documentation is inconsistent about which pins are for MOSI and MISO on the secondary SPI port (which is the only one I could enable successfully). This will at least give a good stepping off point for anybody who wants to work on it.

Add BeagleBone AI Support

---

requirements.txt

Needed since 8273fc6, otherwise you will get:
```
AttributeError: module 'adafruit_platformdetect.constants.chips' has no attribute 'DRA74X'
```

update minimum version of Adafruit-PlatformDetect

---

src/adafruit_blinka/microcontroller/bcm283x/pin.py

For #410.
Removes an entry that allowed use of a very specifically configured `i2c-gpio` port which could then mask the existing default hardware port, for cases where both were trying to be used.

Remove I2C bus 3 from BCM283x

---

src/adafruit_blinka/board/nanopi/duo2.py
src/board.py

This adds nanoPi Duo2 to usable boards.

adds pin PG11 i2c, spi, serialUART support for nanoPi Duo2

---

src/adafruit_blinka/microcontroller/ft232h/spi.py
src/adafruit_blinka/microcontroller/nxp_lpc4330/spi.py

This is a tested fix for ft232h and a speculative fix for nxp_lpc4330. I used the Adafruit FT232H breakout (current version, w/USB-C and Stemma connector) and the Adafruit "microSD SPI or SDIO" breakout for my most recent round of testing. The connections were D0/D1/D2 for the SPI signals and D4 for the Chip Select signal. I used Linux as my host computer.
@gerd1986 please let us know whether this change allows you to access the SD card with the FT232H interface.
I tested with the following script:
```python
import board
import digitalio
import adafruit_sdcard
cs = digitalio.DigitalInOut(board.D4)
bus = board.SPI()
card = adafruit_sdcard.SDCard(bus, cs)
print("capacity (in 512-byte blocks", card.count())
buf = bytearray([0]) * 512
card.readblocks(0, buf)
print("content of first block") …
```

Fix SPI.readinto with write_data=NONZERO

---

setup.py

A recent release of Raspberry Pi OS now has `raspberrypi,4-model-bbrcm,bcm2711` in `/proc/device-tree/compatible`.

Fix recent RaspiOS not installing RPi.GPIO

---

src/adafruit_blinka/microcontroller/ft232h/pin.py

#423 
Class Pin of FT232H returns NotImplementedError if pull is not None, now.
Constants PULL_NONE, PULL_UP and PULL_DOWN are defined, now.

Fix #423 FT232H Pin returns NotImplementedError

---

src/microcontroller/__init__.py

I wrote a [CircuitPython library](https://github.com/dhalbert/CircuitPython_LCD) a long time ago that uses `microcontroller.delay_us()`. Someone wanted to use it on an RPi, and could not use it without modification because `microcontroller.delay_us()` does not exist in Blinka. This adds it, just calling `time.sleep()` to simulate it.
I can't use `time.sleep()` in the original library because it is only accurate to the nearest millisecond. Values smaller than a millisecond are rounded, so, for instance a few hundred microseconds is no delay at all.

add microcontroller.delay_us()

---

src/board.py

The original BeagleBone is same SoC (AM3358) as Black and Green and similar layout in terms of the cape headers.  It should just work once the EEPROM ID for original BeagleBone models is added this conditional logic.  Refer to issue #439

Add support for the orignal BeagleBone #439

---

src/adafruit_blinka/microcontroller/bcm283x/pin.py

Added I2C bus 10 definition for the Raspberry Pi CM4.
I tested the change on my own CM4 on a custom carrier board and a SSD1306 display and it works fine.
This PR was inspired by this one:
https://github.com/adafruit/Adafruit_Blinka/pull/83
The pins for the I2C bus on the CM4 are described in its datasheet, but the subject is also discussed here:
https://www.raspberrypi.org/forums/viewtopic.php?t=296162
This is my first contribution to an open source project, apologies if I omitted something!

Added internal I2C bus for the CM4

---

README.rst

Updates the README to make clear this emulation works on both CPython and MicroPython.
Fixes #369.

Make clear in README Blinka works on CPython and MicroPython

---

src/adafruit_blinka/microcontroller/ft232h/i2c.py
src/adafruit_blinka/microcontroller/ft232h/pin.py
src/adafruit_blinka/microcontroller/ft232h/spi.py
src/adafruit_blinka/microcontroller/ft232h/url.py

This allows the an FTDI URL, like ftdi://ftdi:232h:W00001/1
to be given in the BLINKA_FT232H. If it's used, then that
board is the one that is opened. If the value of the variable
is not an FTDI url, then the default is used.
This makes it possible for multiple processes on the same
computer to talk to different FTDI boards. While talking
to multiple boards from a single process might be possible,
that's outside of the scope of this commit.

Add support for ftdi URLs in the BLINKA_FT232H variable.

---

src/adafruit_blinka/microcontroller/bcm283x/pin.py

Currently the additional SPI ports on the Pi4 or CM4 are not usable in Blinka without doing this change manually.
SPI6 uses the same pins as the default SPI1 pins.

Add additional SPI ports for BCM2711

---

.gitignore
src/adafruit_blinka/microcontroller/rp2040/i2c.py

This should hopefully fix any libraries that use `adafruit_register` to access registers over I2C.
I've tested it with an Adafruit DPS310.
Please test it with other driver libraries that use `adafruit_register`.

Fix I2C writeto_then_readfrom when in_start > 0 in RP2040

---

src/adafruit_blinka/board/beagleboard/beaglev_starlight.py
src/adafruit_blinka/microcontroller/starfive/JH71x0/__init__.py
src/adafruit_blinka/microcontroller/starfive/JH71x0/pin.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

I added the new BeagleBone StarLight to Blinka and have GPIO and I2C working.
I also reduced the huge if/else tree in busio for SPI by making use of the any_embedded_linux property for anything else that's not caught ahead of that for loading up specialized constructors. That way we don't have an extra 20-30 if checks just to import the same line of code.

Added BeagleBone StarLight to Blinka (GPIO, I2C working)

---

src/adafruit_blinka/microcontroller/generic_linux/spi.py
src/digitalio.py

Update digitalio docstrings to be more in line with CircuitPython

---

.github/workflows/release.yml
setup.py
src/analogio.py
src/bitbangio.py
src/board.py
src/busio.py
src/digitalio.py
src/keypad.py
src/micropython.py
src/neopixel_write.py
src/pulseio.py
src/pwmio.py
src/rainbowio.py

Add version munging to the top-level Python files so that when a new version is released the files uploaded to PyPI will have a `__version__` and `__repo__` variable similar to the CircuitPython ones.
eg, `busio.__version__ = 6.14.0`
There is also a special variable only added to `board` for now:
`board.__blinka__ = True`
This is to make it easy for a library to determine if it is being run on Blinka.
Tested by uploading a dummy release to:
https://pypi.org/project/samourai-Adafruit-Blinka/

Add versioning to the top-level Python files

---

.github/workflows/release.yml
setup.py
src/analogio.py
src/bitbangio.py
src/board.py
src/busio.py
src/digitalio.py
src/keypad.py
src/micropython.py
src/neopixel_write.py
src/pulseio.py
src/pwmio.py
src/rainbowio.py

Reverts adafruit/Adafruit_Blinka#508. We realized this shouldhave only applied to board.

Revert "Add versioning to the top-level Python files"

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

This fix allow sending I2C transactions with an empty payload.
Before this change, sending an empty payload is bogus as it won't transfer
anything but will still try to get the status of the transaction. It will
basically get the current status of the bus.
One way to manifest this problem is when connecting to a device.
On `I2CDevice` init, it will [probe the device by sending en empty payload](https://github.com/adafruit/Adafruit_CircuitPython_BusDevice/blob/b869a4a12618721f1232cbbec95a6186fb84ddf7/adafruit_bus_device/i2c_device.py#L154)
message. This actually works fine if the bus is in a good state like on
first use. It won't actually send the probe out but we will read the
good initial state and things will go smoothly from here.
However if we start by initializing a device with an …

mcp2221: allow empty i2c payload

---

src/board.py

Hello Adafruit Blinka maintainers team! 
I have a [Beaglebone Green Gateway board](https://www.seeedstudio.com/SeeedStudio-BeagleBone-Green-Gateway-p-4586.html) that I would like to use Blinka on! It seems trivial to add it, so I've added support here using the same pattern that is used to add support for the Beaglebone Green!
I have submitted my change here. Let me know if this looks good or if anything needs changing!

#525 Add Beaglebone Green Gateway Board Support

---

.github/workflows/build.yml
docs/conf.py
setup.py

This updates the version of python that will get used in the actions container to 3.7. This is needed to avoid an issue currently affecting debian builds. It's discussed a bit more here: https://github.com/adafruit/Adafruit_Blinka_Displayio/pull/73

change actions to use python 3.7

---

src/microcontroller/__init__.py

Allow successful import on `GENERIC_X86`. Warn that all features may not work.

add case for generic_x86

---

src/microcontroller/__init__.py

Hi,
I am using the Adafruit MCP2221 breakout board to connect my Mac to I2C devices.
However when I try to import the library adafruit_ads1x15 it would raise the following error:
NotImplementedError: ('Microcontroller not supported:', 'MCP2221')
I noticed that the import in the __init__.py for the MCP2221 was missing compared to what is in pin.py.
After adding the missing import, I was able to use the ADS1015 with the MCP2221 as expected.
I checked if there were any other missing imports, and there were none. The only thing was that __init__.py prints a warning for GENERIC_X86 whereas pin.py doesn't.
Not really sure what the process is for testings etc. on this repository. If there are specific guidelines on raising a PR, then please let me know.
Kind regards,
Andre

Missing Pin imports for the MCP2221

---

docs/api.rst
docs/requirements.txt
requirements.txt
setup.py
src/_typing.py
src/circuitpython_typing.py

Address inability to use CircuitPython's typing module `_typing` (which will become `circuitpython_typing`) by adding a subset of the module.  In CircuitPython these are stub files, as my understanding is that these are purely conceptual (`bytearray` of course is a real thing, but a `ReabableBuffer` isn't and is just a way of communicating things that implement the buffer reading protocol).
This will works for CircuitPython, because adding the too the `try`/`except` block were using for typing in libraries means that it will never actually try to import the library, while the computer environment used to write code **will** be able to and will access the stubs.  However, since the `try`/`block` is intended to fail by importing the CPython `typing` library, platforms running Blinka won't …

Add typing module(s) to Blinka

---

src/circuitpython_typing.py

Hotfixes issues with `adafruit_bus_device` and other libraries that are importing `circuitpython_typing` on Blinka platforms!

Remove numpy import

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

This PR addresses the first point of #536.  The [`hidapi` docs](https://trezor.github.io/cython-hidapi/api.html#hid.device.close) mention explicitly that `device.close()` "should always be called after opening a connection".
To address this issue, I first created a new public `MCP2221.close()` method.  This has three advantages:
1. the user can close the device directly;
2. the method can be used as a callback to close the currently-open device (using `atexit.register(self._hid.close)` doesn't work if `self._hid` gets reassigned);
3. the class becomes usable as a context manager through `contextlib.closing` (even though it might be better to explicitly support the context-manager protocol by adding `__enter__` and `__exit__`).
I then called this method in 3 places, to ensure the device is …

Close the mcp2221 device before exit.

---

.pre-commit-config.yaml
src/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py
test/src/testing/universal/i2c.py

Fixes #571. Fixes #425. Tested on Odroid C2 with older and newer libgpiod.

Allow older and newer versions of libgpiod to work, Allow Pullups

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py
src/adafruit_blinka/microcontroller/rp2040_u2if/rp2040_u2if.py

Fix for #573.
Pretty simple, just need to explicitly close when resetting. Tested locally to recreate original issue and verify this patch worked to fix. Even blinked an LED to make sure.

Close HID connnection to MCP2221 when resetting

---

requirements.txt
setup.py

Fixes #580 by adding `adafruit-circuitpython-typing` to `setup.py` and `requirements.txt`.  I don't think a specific version is needed, and the few libraries that require features that weren't in base (really anything other than `ReadableBuffer` and `WriteableBuffer`) and had them added to that library will have to call those out and pin to minimum versions anyway.

Require adafruit-circuitpython-typing on install

---

src/microcontroller/__init__.py
src/microcontroller/pin.py

This PR allows blinka to run on non-embedded systems, i.e. GENERIC_LINUX or Windows Environments. The motivation was to allow the use of the displayio library on non-circuitpython boards. (See https://github.com/adafruit/Adafruit_Blinka_Displayio/pull/63 for a discussion about this use-case). This allows the library to be used to create general-purpose desktop GUIs, as well as to simulate a hardware display so that embedded GUIs can be developed and tested without physical hardware.
Instead of failing with a `NotImplementedError` if the platform's `chip_id` is `None` or `'GENERIC_X86'`, I print a warning message. In order to satisfy the `Pin` import in `pin.py`, I imported the class from `generic_micropython`. This might not be the best thing to do here, since the platform is not …

Allow Blinka to run on non-embedded environments

---

src/adafruit_blinka/board/radxa/radxazero.py
src/adafruit_blinka/microcontroller/amlogic/s905y2/pin.py
src/board.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

- Maps GPIO lines to GPIO numbers
- Define relevant constants for GPIO pins and protocols
[reference](https://wiki.radxa.com/Zero/hardware/gpio)

Add support for Radxa Zero - S905Y2

---

docs/api.rst
setup.py
src/busio.py
src/onewireio.py

We have moved `OneWire` to its own module in CircuitPython, so we can easily turn it on and off
In CircuitPython 6.x.x, `OneWire` was available  as `busio.OneWire`.
In CircuitPython 7.x.x, `OneWire` is available as `busio.OneWire` _and_ as `onewireio.OneWire`.
In CircuitPython 8.x.x, `OneWire` will be available  only as `onewireio.OneWire`.
Have Blinka catch up to `onewireio.OneWire`. Note that `OneWire` is still unimplemented in Blinka
@makermelissa Do you want this to be a major version change? It's an API change, but for a piece of the API that's unimplemented. But integers are free.

Move (unimplemented) OneWire from busio to onewireio

---

src/usb_hid.py

As per python docs:
> For reading and writing raw bytes use binary mode and leave encoding unspecified
```py
>>> open("test", "rb+", encoding="utf-8")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: binary mode doesn't take an encoding argument
>>> 
```

usb_hid: open in binary does not take an encoding

---

setup.py
src/micropython-stubs/micropython.pyi

This allows use of micropython.const to typecheck without making any changes to the .py files themselves. It's an alternative to #608

Provide stubs for micropython module in a more clearly compatible way

---

.github/workflows/build.yml
.github/workflows/release.yml
src/__version__.py
src/board.py

1. CI will not fix version strings before uploading to PyPI!
2. Now builds pure Python wheels as well besides uploading source distributions, which hopefully speeds up installation

Update version on release

---

.github/workflows/release.yml

This should fix the problem with `build` missing.  Tested locally and worked.

Fix build missing in release CI

---

src/adafruit_blinka/board/siemens/__init__.py
src/adafruit_blinka/board/siemens/siemens_iot2050.py
src/adafruit_blinka/microcontroller/am65xx/analogio.py
src/adafruit_blinka/microcontroller/am65xx/i2c.py
src/adafruit_blinka/microcontroller/am65xx/pin.py
src/adafruit_blinka/microcontroller/am65xx/pwmout.py
src/adafruit_blinka/microcontroller/am65xx/spi.py
src/analogio.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py
src/pwmio.py

Hello,
I added support for GPIO, AIO, I2C, SPI, UART, PWM, NeoPixels for the Siemens Simatic [IOT2050 SBC](http://www.siemens.com/iot2050)
I added my MIT Licence Informations to the Files I heavily modified and for files with only few changes I extend the licence informatons  -> am65xx/pin.py ; am65xx/pwmout.py.
thanks
best regards
Martin Schnur

Added support for Siemens Simatic IOT2050 Basic/Advanced

---

src/adafruit_blinka/board/bananapi/bpim2plus.py
src/board.py

This PR adds support for the Banana PI M2 Plus. Have been using and testing these changes for a few weeks with no issues so far though I arguably have not tested all of the different pin functions. Can confirm that i2c, basic gpio, and spi work.

Adding support for Banana PI M2 Plus

---

src/digitalio.py

Digitalio was supposed to be mostly chips from the platform detect because we're importing the chip info here. This fixes that.

Fix digitalio maintenance by removing non-special case boards

---

src/board.py

The "if query" for the SIMATIC IOT2050 Basic was missing.
It could be tested now with the new version of the SIMATIC IOT2050 Basic (FS:04 12.2022)
thanks
best regards
Martin Schnur

Added missing if query for Siemens SIMATIC IOT2050 Basic Version -> updated board.py

---

src/adafruit_blinka/board/generic_linux_pc.py
src/board.py

This pull requests adds minimal support for boards with id 'GENERIC_LINUX_PC'. With this patch, an `import board` no longer fails and `board.board_id` is something to work with.
I am using this together with @FoamyGuy s <https://github.com/FoamyGuy/Blinka_Displayio_PyGameDisplay> package to run CircuitPython-code on a normal linux-box (mainly to create screenshots). With this patch, `import board` does not fail anymore.

Minimal support for generic linux pc

---

src/adafruit_blinka/board/orangepi/orangepi4.py

In this pull request I have updated pinout for OrangePi4 board.
In the previous PR (https://github.com/adafruit/Adafruit_Blinka/pull/612) the pinout was incorrect

Update orangepi4 board

---

src/adafruit_blinka/board/beagleboard/beaglebone_blue.py
src/board.py

Hi, I needed to use I2C on the BeagleBone Blue, so I added support for that in the library.  This pr only includes pins that I have tested personally, but someone with more knowledge about the blue might be able to fill in the blanks.  According to [this](https://github.com/adafruit/adafruit-beaglebone-io-python/issues/313#issuecomment-513904700), it might be pretty similar to the black, but I don't know anything for sure.  Would the maintainers want a partially supported board like this included in the official library or kept as a fork?

Added minimal beaglebone blue support

---

src/adafruit_blinka/board/coral_dev_board.py

I needed to use the second I2C port (I2C3) and so I added this locally, and it works.

Add second I2C to coral_dev_board.py

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Similar to https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/311. Release Drafter is a GitHub Actions library that allows automatic generation of releases so that it is much easier to create informative release info.

Add Release Drafter to make releases easier

---

.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/feature_request.md.license
.github/ISSUE_TEMPLATE/new_board_request.md
.github/ISSUE_TEMPLATE/new_board_request.md.license

Apparently adding inline SPDX headers breaks the files

Separate SPDX to separate files for issue markdown

---

src/adafruit_blinka/board/hardkernel/odroidn2.py

Add check to ODroid n2 to make sure i2c matches expected ports

---

src/busio.py

I realized the reason the warning was commented out before #708 is because busio uses a default frequency value of 100000 which will always trigger the warning. This will fix it so if the user isn't trying to set the frequency to something besides the default, it won't trigger the warning.

Update busio to avoid always triggering frequency warning

---

setup.py
src/adafruit_blinka/microcontroller/am335x/pin.py

Add better error message and explicity add to setup

---

.readthedocs.yaml

Just like in https://github.com/adafruit/Adafruit_Blinka_Displayio/pull/113, this fixes the failing docs. According to https://blog.readthedocs.com/use-build-os-config/, they are doing a test run today and it will start failing permanently on Oct 16 without this change.

Fix soon-to-be failing docs

---

src/adafruit_blinka/microcontroller/generic_linux/spi.py

Fixes #509. Using a boolean truthy statement wasn't working with Numpy Buffers, but did work using tuples and such. Using len() works with all the types of buffers.

Update SPI to work with ReadableBuffers

---

requirements.txt
setup.py
src/adafruit_blinka/board/raspberrypi/raspi_5b.py
src/adafruit_blinka/microcontroller/bcm2712/pin.py
src/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/pin.py

This adds support for the Raspberry Pi 5 as well as the Compute Module 4S (untested). RPi.GPIO is not currently working on the Pi 5 and since we already had a pin for libgpiod, I went with that. In order to maintain compatibility, I updated the code to fix the pullups and pulldowns, which should be helpful for other boards that use libgpiod.

Added Pi 5 Support + Fixed libgpiod pulls

---

src/adafruit_blinka/board/hardkernel/odroidm1s.py
src/adafruit_blinka/microcontroller/rockchip/rk3566/pin.py
src/board.py

i2c0, spi and uart are not available as default values because they are provided as aliases.

New Support for ODROID-M1S

---

src/adafruit_blinka/board/orangepi/orangepi5plus.py
src/board.py

I based the new module OrangePi5Plus.py on documentation provided by Orange Pi, from it's wiki page for the 5 plus. I am confident of the the GPIO mappings, but less so with the UART, I2C, PWM settings, as they match the Orange Pi values provided, but seem to conflict with the values in src/adafruit_blinka/microcontroller/rockchip/rk3588/pin.py.

Add constants and board selection for Orange Pi 5 Plus

---

src/adafruit_blinka/microcontroller/alias.py
src/adafruit_blinka/microcontroller/amlogic/meson_g12_common/pin.py
src/adafruit_blinka/microcontroller/rockchip/rk3566/pin.py
src/adafruit_blinka/microcontroller/rockchip/rk3568b2/pin.py
src/microcontroller/pin.py

Use rk3568 instead of rk3568b2:
- https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/331

ODROIDs: Support aliased alt functions

---

src/adafruit_blinka/microcontroller/generic_linux/sysfs_pwmout.py

The 'deinit' function is called each time a property value is read and written.
However, the duty cycle continues to reset, so the sysfs PWM does not work properly.

generic_linux: pwmout: Remove duty-cycle reset in deinit flow

---

src/adafruit_blinka/microcontroller/generic_linux/libgpiod/libgpiod_pin_1_x.py
src/adafruit_blinka/microcontroller/generic_linux/libgpiod/libgpiod_pin_2_x.py
src/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py

Fixes #740. Version is automatically detected and the appropriate version is loaded. Tested on 1.5.4, 1.6.3, and 2.1.3.

This adds support for libgpiod 2.x without breaking support for 1.x

---

src/adafruit_blinka/microcontroller/amlogic/meson_g12_common/pin.py
src/adafruit_blinka/microcontroller/rockchip/rk3566/pin.py
src/adafruit_blinka/microcontroller/rockchip/rk3568b2/pin.py

Character parsing index error.
Uart serial is aliased as SERIAL'X'
At the same time as fixing the error, I changed all the indexing to unify the format.

ODROID-COMMON: Fix error of importing board

---

src/adafruit_blinka/board/hardkernel/odroidc4.py
src/adafruit_blinka/board/hardkernel/odroidm1.py
src/adafruit_blinka/board/hardkernel/odroidm1s.py
src/adafruit_blinka/board/hardkernel/odroidn2.py
src/adafruit_blinka/microcontroller/amlogic/meson_g12_common/pin.py
src/adafruit_blinka/microcontroller/rockchip/rk3566/pin.py
src/adafruit_blinka/microcontroller/rockchip/rk3568b2/pin.py
src/analogio.py

e.g.
```
import time
import board
from analogio import AnalogIn
analog_in = AnalogIn(board.A0) # support A0 and A1.
def get_voltage(pin):
return (pin.value * 1.8) / 1024
while True:
print((get_voltage(analog_in),))
time.sleep(0.1)
```

ODROID-COMMON: Support ADC pins

---

src/microcontroller/pin.py

Yep, it worked because
```python
"abc" in "abc"  # is True
```
But I guess the idea was to check if it's one of the boards (and for now the tuple of boards has only one member)
Same as:
https://github.com/adafruit/Adafruit_Blinka/blob/fde264375432951da98131182e9b00a177b2f3c1/src/microcontroller/pin.py#L27

Fix ODROID_M1 board detection

---

src/adafruit_blinka/board/repkapi/repka_pi_3.py
src/adafruit_blinka/board/repkapi/repka_pi_4.py
src/board.py
src/microcontroller/pin.py

Repka-Pi 3 H5 differs from the standard H5 pinout. Add pinout to the lib
This PR depends on another PR in the PlatformDetect library https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/336
Pipelines will stay red until PlatformDetect is updated

Add support for Repka Pi-3 H5 and Pi-4 H6 boards

---

src/adafruit_blinka/microcontroller/generic_linux/libgpiod_pin.py

With https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/commit/bc4b07e658fe287951a372df236edd62b522af97#diff-642f752e075338833f3d09557b0c3ee40d8b31041f7a478d0c24df8f71261e16 the location of the libgpiod.sh script changed.
Additionally, a libgpiod.py script appeared in https://github.com/adafruit/Raspberry-Pi-Installer-Scripts/commit/210dcee1389ab142588ec8afb1eec298982cd989 and is more maintained.
So it seems better to suggest using the latter.

Corrected URL of libgpiod install script

---

src/adafruit_blinka/microcontroller/amlogic/meson_g12_common/pin.py
src/adafruit_blinka/microcontroller/generic_linux/libgpiod/libgpiod_chip_1_x.py
src/adafruit_blinka/microcontroller/generic_linux/libgpiod/libgpiod_chip_2_x.py
src/adafruit_blinka/microcontroller/generic_linux/libgpiod_chip.py

After an upgrade of my python environment I got issues with libgpiod
A quick search learned me that libgpiod has been updated again with breaking changes
The same issue was already faced with RPI5 in issue https://github.com/adafruit/Adafruit_Blinka/issues/740
I much like the clean and neat approach taken with libgpiod_pin and made an attempt to mimic the same in libgpiod_chip for supporting multiple libgpiod versions on Odroid C4 (meson_g12_common).
Do note that in the past I created some regression causing issue https://github.com/adafruit/Adafruit_Blinka/issues/685
All this logic is now in libgpiod_chip.py, so I hope it didn't break anything. As @how2flow is also very active lately I hope he might also have a peak at it.
This approach could also be used …

libgpio 2.x support for odroid c4

---

src/pwmio.py

PWMIO is not working on the Pi 5 at the moment (see #776). This is more of a stopgap measure to at least show a more appropriate error until it has been fixed.

Show NotImplementedError for pwmio on the Pi 5 for now

---

setup.py
src/pwmio.py

Fixes #776. This fixes PWM, by installing rpi-lgpio for the Pi 5, which is a drop-in replacement for RPi.GPIO. Then Blinka can effective make use of the code for the Pi 4 and earlier.

Update Blinka to use rpi-lgpio for PWM

---

src/adafruit_blinka/board/generic_agnostic_board.py
src/adafruit_blinka/microcontroller/generic_agnostic_board/neopixel.py
src/adafruit_blinka/microcontroller/generic_agnostic_board/pin.py
src/adafruit_blinka/microcontroller/generic_agnostic_board/spi.py
src/analogio.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py
src/neopixel_write.py
tests/test_generic_agnostic_board_analogio.py
tests/test_generic_agnostic_board_digitalio.py

This pull request:
- Supports the OS-agnostic board via PlatformDetect instead of using `FORCE_x` variables.
- ref: https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/353
- Adds SPI, NeoPixel, and DotStar support to this board
- Note that this work was originally in https://github.com/adafruit/Adafruit_Blinka/pull/831
Result from running pytest across this PR using the tests within `tests/`:
```
================================================================== test session starts ===================================================================
platform darwin -- Python 3.12.2, pytest-8.2.1, pluggy-1.5.0
rootdir: /Users/brentrubell/Desktop/github_brentru/Adafruit_Blinka
collected 12 items
tests/test_generic_agnostic_board_analogio.py ..... …
```

Support for generic board via PlatformDetect

---

src/busio.py

Fixes SPI configuration for the generic OS board by adding extra detection to to the `busio` `configure()` method

Fix SPI on generic board

---

src/adafruit_blinka/board/luckfox/luckfoxpico_mini.py
src/adafruit_blinka/microcontroller/rockchip/rv1103/__init__.py
src/adafruit_blinka/microcontroller/rockchip/rv1103/pin.py
src/analogio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

I tested this PR with LuckFoxPicoMax and LuxkFoxPicoMini.
https://github.com/adafruit/Adafruit_Blinka/pull/841
LuckFoxPicoMax works fine.
But I found the problem on LuckFoxPicoMini and fixed it.

LuckfoxPicoMini changed from RV1106 to RV1103

---

src/adafruit_blinka/microcontroller/generic_agnostic_board/PWMOut.py
src/pwmio.py

`PWMOut` implementation for the Generic Agnostic Board. For this board, the `PWMOut` class is a mock PWM output interface for use with software (CI) testing.

Add PWMOut Support for Generic Agnostic Board

---

setup.py

platform.machine() is a function rather than a property. This is to address #858.

Fix platform.machine check in setup.py

---

setup.py

This is an attempt to fix sysv-ipc trying to install on windows

Use platform.system instead of sys.platform for setup.py

---

setup.py

This is an attempt to address #858.

Fix sysv_ipc issue by moving to compatible string checks

---

setup.py

This is an attempt to make the install more consistent with 8.43.0.

Improve sysv_ipc fix by using requirements syntax

---

.github/workflows/release.yml

In short, bdist (binary distributions) created from a pure python project are universal. They cannot be made to use a platform-specific tag (like linux, windows, macos, etc). This changes the release CI workflow to skip creating/uploading a bdist to PyPI.
This library has a number of dependencies conditionally required per *machine* attributes (like CPU type). But pip (or other python package managers) will not be aware of such conditional dependencies because a universal bdist do not invoke a dynamic resolution of machine-specific dependencies. Universal bdists only resolve platform-specific dependencies (python version, system OS, etc) which isn't sufficient for this library. Instead, this paradigm is better left to a sdist (source distribution) which carry dependency details per …

don't upload universal bdist to pypi

---

.github/workflows/release.yml

Reverts adafruit/Adafruit_Blinka#863 because of slow installs and additional requirements making this more support heavy.

Revert "don't upload universal bdist to pypi"

---

src/adafruit_blinka/microcontroller/mcp2221/mcp2221.py

The MCP2221 reports a `RuntimeError` when the `i2c_scan` function encounters a failure. This differs from CircuitPython, where it throws an `OSError`. Further, [most sensor drivers with a "double-retry"](https://github.com/adafruit/Adafruit_CircuitPython_MAX1704x/pull/10/files) (see [this driver](https://github.com/adafruit/Adafruit_CircuitPython_MAX1704x/pull/10/files))  are written to catch an `OSError`, rather than a `RuntimeError`.
This PR raises an `OSError` for the MCP2221 platform where it's expected, to fix I2C devices not initializing or being scanned correctly.
I've tested it with the MCP2221 and the MAX17048 as has @tyeth 
Related:
https://github.com/adafruit/Adafruit_Wippersnapper_Python/issues/173
https://github.com/adafruit/Adafruit_Wippersnapper_Python/pull/172#issue-2360866 …

Fix MCP2221 I2C NACK Error

---

src/adafruit_blinka/microcontroller/amlogic/s905y2/pin.py

I add some pinout support for Radxa Zero PWM.
Below I share how I found the mapping between PWM chip and GPIO numbers.
1. Check mapping between device file and GPIO number
```
$ sudo cat /sys/kernel/debug/pinctrl/ff800000.sys-ctrl:pinctrl@14-pinctrl-meson/pinmux-pins | grep pwm
pin 11 (GPIOAO_11): ff807000.pwm (GPIO UNCLAIMED) function pwm_ao_a group pwm_ao_a
```
2. Find out the chip number corresponding to the device file
```python
In [1]: from adafruit_blinka.microcontroller.alias import get_pwm_chipid
In [2]: get_pwm_chipid("ff807000.pwm")
Out[2]: 'PWM2'
In [3]: int(get_pwm_chipid("ff807000.pwm")[-1])
Out[3]: 2
```
3. Add pinout mapping to pin.py
```python
pwmOuts = (
((2, 0), GPIOAO_11),  # ((chip, channel), GPIO)
)
```

Add some pinout support for Radxa Zero PWM

---

setup.py

Fixes #872. Numpy seems to no longer be needed as of #552.

Remove unused numpy as requirement

---

src/adafruit_blinka/board/rp2040_one_u2if.py
src/adafruit_blinka/board/wvsh_rp2040_one_u2if.py
src/board.py

Part of a trio of PRs to see support for the RP2040 One extended; I think it could be useful as an inexpensive entry to testing out sensors or debugging in light of articles such as:
https://learn.adafruit.com/circuitpython-libraries-on-any-computer-with-raspberry-pi-pico
Companion pull requests:
https://github.com/adafruit/u2if/pull/11
https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/366

Include Waveshare RP2040 One (2 of 3)

---

src/keypad.py

Renamed `keypad._EventQueue` to `keypad.EventQueue` for parity with CircuitPython.
Fixes #882

Renamed keypad._EventQueue for parity with CircuitPython

---

.github/workflows/build.yml
src/board.py
src/neopixel_write.py

This adds support for the Pi500, CM5, and CM5 lite. Tested on Pi500 including running Neopixels. Simplified some of the import board checks so future boards can just be added to platformdetect.
Requires https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/377.
Fixes #922. Fixes #919.

Add Pi500 and CM5 Support

---

src/rotaryio.py

I decided to go with a threading/poll method as this will work more universally across boards. In the future, I may optimize this by implementing interrupts where available (such as using the raspberry pi's Rpi.GPIO package).

Add rotaryio module

---

src/board.py

Added support for Orange pi 5 Max which has same pin layout as orange pi 5
depends on https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/380

added support for orange pi 5 max

---

src/adafruit_blinka/board/radxa/rock3b.py
src/board.py

Dependency with https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/381 that must be merged first.
Tested Radxa Rock3B running `Linux rock-3b 5.10.160-18-rk356x`.

Add Radxa Rock 3B board

---

src/adafruit_blinka/board/ftdi_ft4232h.py
src/adafruit_blinka/microcontroller/ftdi_mpsse/ft4232h/pin.py
src/adafruit_blinka/microcontroller/ftdi_mpsse/mpsse/i2c.py
src/adafruit_blinka/microcontroller/ftdi_mpsse/mpsse/pin.py
src/adafruit_blinka/microcontroller/ftdi_mpsse/mpsse/spi.py
src/adafruit_blinka/microcontroller/ftdi_mpsse/mpsse/url.py
src/board.py
src/busio.py
src/digitalio.py
src/microcontroller/__init__.py
src/microcontroller/pin.py

Depends on https://github.com/adafruit/Adafruit_Python_PlatformDetect/pull/382
Non-backwards compatible changes:
- Rename BLINKA_FT2232H_x environmentr variable(s) into BLINKA_FTX232H_x
>Perhaps acceptable since related feature is poorly documented and is only mentioned [here](https://github.com/adafruit/Adafruit_Blinka/pull/437#issuecomment-838020882).

Add support to FT4232H

---

src/adafruit_blinka/microcontroller/bcm283x/neopixel.py

Adds support for NeoPixel on PWM1 pins (13, 19, 41 and 45) on Raspberry Pis.

neopixel_write: add support for PWM1 pins on Raspberry Pis

---

src/adafruit_blinka/microcontroller/generic_linux/lgpio_pin.py

When using a USB to Serial cable I note that initialising the blinka library would crash. I'd receive an error saying that it cannot open the file `/sys/bus/gpio/devices/gpiochip14/of_node/compatible`. This was because the FTDI cable had added an additional gpioChip which didn't have the expected path structure. 
I feel like it's safe to add an `is_file()` check to this path before opening and this does make the issue go away on my setup.
Please let me know if there are:
- Coding standards I may have missed
- Tests that I need to run and ensure I haven't broken
- A better way to handle this
Additionally, is it worth looking if we do this sort of blind read elsewhere and fix those too? Could then add a generic function.

fix compatibility with differing `/sys/bus/gpio/devices/gpiochip*`

---

pyproject.toml

I think this resolves: #975 
with this change I tested locally by doing `pip install .` and then going to the REPL and I can now successfully run `import digitalio` 
All testing was ubuntu 24.04 under python 3.12
Perhaps this makes the items that follow it in the packages list redundant though? Maybe those could be removed, I didn't try it, and they look potentially hardware dependent so I'm not sure how to test if we do remove them.

include adafruit_blinka package in build

---

requirements.txt

I did a quick test and confirmed that this allows adafruit-blinka to be installed under py3.13. I assume the actual gpio functionality on rp5 would not work in that environment, but installing blinka and importing modules seems to and that should be good enough for our docs builds I believe.

dont require lgpio on python 3.13+

---

setup.py

In certain cases, pip install fails. This is because one of the requirements (sysv_ipc) requires the python3 dev headers. This adds a check to the setup files to point the user in the correct direction.

Check for Python.h file needed for sysv_ipc

---

src/micropython-stubs/__init__.pyi

`micropython.const` now supports any constant type, not just `int` (https://github.com/micropython/micropython/pull/8548). This updates the type checking to reflect this. This also updates the name of the file so that type checkers can find it.
This was discussed in https://github.com/adafruit/circuitpython/issues/10484.

Make micropython.const accept any constant type

---

src/adafruit_blinka/microcontroller/generic_linux/libgpiod/libgpiod_pin_2_x.py

The libgpiod changes in #1001 caused digitalio to be unable to change a pin from input to output (or vice versa) once configured. This undos those changes.

Rollback breaking libgpiod changes from #1001
